### ISSUE TITLE
I like it. Missing example.php

### ISSUE THREAD

**Issue by halojoy** [Josantonius/PHP-Cookie#2]
I like your Class very much.
What I miss is some practical real life examples.
I dont know if most would think this is necessary.
But I personally would like you to add at least one example of how to use it.
Can be in the readme file or in a separate example.php.

Thanks for sharing your code.

**Comment by josantonius** [comment]
Hi @halojoy,

Thank you for your feedback.

In reality the use is very simple, I think that with the [documentation](https://github.com/Josantonius/PHP-Cookie#available-methods), [usage examples](https://github.com/Josantonius/PHP-Cookie#usage) and [tests](https://github.com/Josantonius/PHP-Cookie/blob/master/tests/CookieTest.php) should be enough to use this class.

I give you an example:

**Get cookies prefix**:

`Cookie::getPrefix(); // jst_`

**Set cookies prefix**:

`Cookie::setPrefix('coo_'); // true`

**Set cookies**:

```
Cookie::set('cookie_one', 'Value for cookie one', 8); // Expires in 8 days
Cookie::set('cookie_two', 'Value for cookie two');    // Expires in 365 days
```

**Get value from cookie**:

`Cookie::get('cookie_one'); // Value for cookie one`

**Get value and destroy cookie**:

`Cookie::pull('cookie_two'); // Value for cookie two`

**Obtain all user cookies**:

`Cookie::get(); // ["coo_cookie_one"] => "Value for cookie one"`

**Destroy one cookie**:

`Cookie::destroy('cookie_one'); // true`

**Destroy all cookies**:

`Cookie::destroy(); // true`
