### ISSUE TITLE
Check if cookie exists

### ISSUE THREAD

**Issue by jasminder** [Josantonius/PHP-Cookie#4]
If a cookie doens't exist, it returns all the cookies in response. How should we just check if a cookie exists ?

**Comment by cacharrin** [comment]
Yup, i just faced the same problem... bad design. It should return null.

**Comment by simonmwangi16** [comment]
Also get this issue. Need a fix ASAP

**Comment by pixxelfactory** [comment]
I created a pull-request, i introduced a "has" method that checks if the specified key does exist, and changed a couple of things in the get method:
If the key is set to false, then return the whole cookie is returned, but if the key is not empty and does not exist, it simply returns false.

**Comment by josantonius** [comment]
This was not fixed in version 1.x. That version is now deprecated and unsupported. This bug should not occur in the new version (v2.x).
